#!/bin/bash

# Define command-line arguments like pods, deployments, daemonsets, replicaset, job or all

RESOURCE_TYPE=$0
#RESOURCE_TYPE=pods

# Retrieve resource usage statistics from Kubernetes and output the statistics to the console

kubectl get $RESOURCE_TYPE -n kube-system -o custom-columns=RESOURCE:.kind,NAMESPACE:.metadata.namespace,NAME:.metadata.name,CPU:.spec.containers[*].resources.requests.cpu,MEMORY:.spec.containers[*].resources.requests.memory
