#!/bin/bash

# Define command-line arguments

#RESOURCE_TYPE=$0
RESOURCE_TYPE=pods

kubectl get $RESOURCE_TYPE -n kube-system -o custom-columns=RESOURCE:.kind,NAMESPACE:.metadata.namespace,NAME:.metadata.name,CPU:.spec.containers[*].resources.requests.cpu,MEMORY:.spec.containers[*].resources.requests.memory

#kubectl get all -n kube-system -o custom-columns=RESOURCE:.kind,NAMESPACE:.metadata.namespace,NAME:.metadata.name,CPU:.spec.containers[*].resources.requests.cpu,MEMORY:.spec.containers[*].resources.requests.memory



#kubectl get pods,deployments,daemonsets,statefulsets -n kube-system -o custom-columns=RESOURCE:.kind,NAMESPACE:.metadata.namespace,NAME:.metadata.name,CPU:.spec.containers[*].resources.requests.cpu,MEMORY:.spec.containers[*].resources.requests.memory


# Retrieve resource usage statistics from Kubernetes
#kubectl $2 $RESOURCE_TYPE -n $1 | tail -n +2 | while read line
#do
  # Extract CPU and memory usage from the output
#  NAME=$(echo $line | awk '{print $1}')
#  CPU=$(echo $line | awk '{print $2}')
#  MEMORY=$(echo $line | awk '{print $3}')

  # Output the statistics to the console
  # "Resource, Namespace, Name, CPU, Memory"
#done